---
# vars file for ca
mom: 192.168.5.11
certs: 
  - ca.crt
  - ca.key
  - kube-apiserver.key
  - kube-apiserver.crt
  - service-account.key
  - service-account.crt
  - etcd-server.key 
  - etcd-server.crt