---
# vars file for ca
mom: 192.168.5.11
certs: 
  - ca.crt
  - ca.key
  - kube-apiserver.key
  - kube-apiserver.crt
  - service-account.key
  - service-account.crt
  - etcd-server.key 
  - etcd-server.crt
kube_configs:
  - kube-controller-manager
  - kube-scheduler
  - kube-proxy
  - admin
worker_configs:
  - kube-proxy.kubeconfig
master_configs:
  - admin.kubeconfig 
  - kube-controller-manager.kubeconfig
  - kube-scheduler.kubeconfig