---
# tasks file for ca
- name: Generate private key for admin user
  command: openssl genrsa -out admin.key 2048
  args:
    chdir: "/home/{{ ansible_ssh_user }}"
    creates: "/home/{{ ansible_ssh_user }}/admin.key"

- name: Create CSR using the private key
  command: openssl req -new -key admin.key -subj "/CN=admin/O=system:masters" -out admin.csr
  args:
    chdir: "/home/{{ ansible_ssh_user }}"
    creates: "/home/{{ ansible_ssh_user }}/admin.csr"
- name: Sign certificate for admin user using CA servers private key
  command: openssl x509 -req -in admin.csr -CA ca.crt -CAkey ca.key -CAcreateserial  -out admin.crt -days 1000
  args:
    chdir: "/home/{{ ansible_ssh_user }}"
    creates: "/home/{{ ansible_ssh_user }}/admin.crt"
