---
- name: Copy Remote-To-Remote (from vm-master-1 to worker-nodes)
  copy: 
    src: "/home/vagrant/{{ item }}" 
    dest: "/home/vagrant/{{ item }}"
    remote_src: yes
  with_items: 
    - "{{ certs }}"
  delegate_to: "{{ mom }}"