---
- name: "Copy generate_{{ item }}_config.bash "
  copy: 
    src: "files/generate_{{ item }}_config.bash"
    dest: "/home/{{ ansible_ssh_user }}/generate_{{ item }}_config.bash"
    mode: u+x
  with_items:
    - "{{ kube_configs }}"
- name: "execute the generate_{{ item }}_config.bash script"
  shell: ./generate_kube-controller_config.bash
  args:
    chdir: "/home/{{ ansible_ssh_user }}"
    creates: "/home/{{ ansible_ssh_user }}/{{ item }}.kubeconfig"
  become: yes
  with_items:
    - "{{ kube_configs }}"
- name: changes file permissions
  file:
    path: "/home/{{ ansible_ssh_user }}/{{ item }}.kubeconfig"
    owner: vagrant
    group: vagrant
  become: yes
  with_items:
    - "{{ kube_configs }}"