---
- name: Copy generate_kube_proxy_config.bash 
  copy: 
    src: files/generate_kube_proxy_config.bash
    dest: "/home/{{ ansible_ssh_user }}/generate_kube-proxy_config.bash"
    mode: u+x
- name: execute the generate_kube_proxy_config.bash script
  shell: ./generate_kube-proxy_config.bash
  args:
    chdir: "/home/{{ ansible_ssh_user }}"
    creates: "/home/{{ ansible_ssh_user }}/kube-proxy.kubeconfig"
  become: yes