---
# tasks file for ca
- name: Generate private key for kube-apiserver user
  command: openssl genrsa -out kube-apiserver.key 2048
  args:
    chdir: "/home/{{ ansible_ssh_user }}"
    creates: "/home/{{ ansible_ssh_user }}/kube-apiserver.key"

- name: Create CSR using the private key
  command: openssl req -new -key kube-apiserver.key -subj "/CN=system:kube-apiserver" -out kube-apiserver.csr
  args:
    chdir: "/home/{{ ansible_ssh_user }}"
    creates: "/home/{{ ansible_ssh_user }}/kube-apiserver.csr"
- name: Sign certificate for kube-apiserver user using CA servers private key
  command: openssl x509 -req -in kube-apiserver.csr -CA ca.crt -CAkey ca.key -CAcreateserial  -out kube-apiserver.crt -days 1000
  args: 
    chdir: "/home/{{ ansible_ssh_user }}"
    creates: "/home/{{ ansible_ssh_user }}/kube-apiserver.crt"
