---
# tasks file for ca
# TODO: make a list of for the configuration of the users, and
# pass the users in through a loop.
- name: Create openssl configuration file
  import_tasks: openssl.yml
- name: Include ca_client_certificate task list in play
  import_tasks: ca_client_certificate.yml
- name: Include admin_client_certificate task list in play
  import_tasks: admin_client_certificate.yml
- name: Include controller_manager_client_certificate task list in play
  import_tasks: controller_manager_client_certificate.yml
- name: Include kube_proxy_client_certificate task list in play
  import_tasks: kube_proxy_client_certificate.yml
- name: Include scheduler_client_certificate task list in play
  import_tasks: scheduler_client_certificate.yml
- name: Include kube_apiserver task list in play
  import_tasks: kube_apiserver.yml
- name: Include etcd_server_certificate task list in play
  import_tasks: etcd_server_certificate.yml