---
# tasks file for ca
- name: Generate private key for service-account user
  command: openssl genrsa -out service-account.key 2048
  args:
    chdir: "/home/{{ ansible_ssh_user }}"
    creates: "/home/{{ ansible_ssh_user }}/service-account.key"
- name: Create CSR using the private key
  command: openssl req -new -key service-account.key -subj "/CN=system:service-account" -out service-account.csr
  args:
    chdir: "/home/{{ ansible_ssh_user }}"
    creates: "/home/{{ ansible_ssh_user }}/service-account.csr"
- name: Sign certificate for service-account user using CA servers private key
  command: openssl x509 -req -in service-account.csr -CA ca.crt -CAkey ca.key -CAcreateserial  -out service-account.crt -days 1000
  args: 
    chdir: "/home/{{ ansible_ssh_user }}"
    creates: "/home/{{ ansible_ssh_user }}/service-account.crt"
