---
## The server needs ssh-pass in order to connect with passwords
### This play is idempotent, but only checks the presence of /etc/kubernetes/kubelet.conf
### It could also verify by running kubectl get nodes and checking hostnames
### looking for ports, and probably some other things.
- hosts: worker_nodes
  vars:
    working_dir: ~/workspace/kube/ansible_pi_kube
    user_group: "{{ ansible_user }}"
  remote_user: root
  gather_facts: false
  tasks:
  #   - name: Create token from control_plane
  #     become: yes
  #     shell: "kubeadm token generate"
  #     register: register_token
  #     delegate_to: "{{ item }}"
  #     with_inventory_hostnames:
  #       - control_plane
  #   - debug: 
  #       var: "{{ register_token.results[0].stdout }}"
  #       verbosity: 2
  #   - set_fact:
  #       token: "{{ register_token.results[0].stdout }}"
  #   - debug: var=token

    # - name: configure a raspberry pi arm64 ubuntu server to be a kube node
    #   include_role:
    # #     name: roles/kube_raspi_ubuntu
    # #     tasks_from: main.yml
     
    - name: Have worker nodes join kube cluster
      include_role:
        name: roles/kube_raspi_ubuntu
        tasks_from: worker_nodes.yml