---
## The server needs ssh-pass in order to connect with passwords
## This play is not idempotent...needs work
### 
- hosts: debug
  vars:
    working_dir: ~/workspace/kube/ansible_pi_kube
    user_group: "{{ ansible_user }}"
  remote_user: root
  gather_facts: false
  tasks:
    - name: configure a raspberry pi arm64 ubuntu server to be a kube node
      include_role:
        name: roles/kube_raspi_ubuntu
        tasks_from: main.yml
    - name: Generate the control_plane kubeadm token
      include_role:
        name: roles/kube_raspi_ubuntu
        tasks_from: control_plane.yml