---
- hosts: vm_mom
  vars: 
    host_key_checking: no
    kubectl_url:  https://storage.googleapis.com/kubernetes-release/release/v1.13.0/bin/linux/amd64/kubectl
  gather_facts: false
  tasks:
  - name: provision certs and tsl
    include_role:
      name: roles/ca
      tasks_from: main.yml
  - name: generate kubeconfigs
    include_role:
      name: roles/ca
      tasks_from: generate_kubeconfigs.yml

- hosts: vm_worker_nodes
  vars:
    role: worker_nodes
  tasks:    
  - name: Copy Remote-To-Remote (from vm-master-1 to worker-nodes)
    include_role:
      name: roles/ca
      tasks_from: copy_certs_and_configs.yml
- hosts: vm_master_nodes
  vars:
    role: master_nodes
  tasks: 
  - name: Copy Remote-To-Remote (from vm-master-1 to master-nodes)
    include_role:
      name: roles/ca
      tasks_from: copy_certs_and_configs.yml
- hosts: vm_load_balancer
  vars:
    role: load_balancer
  tasks:    
  - name: Copy Remote-To-Remote (from vm-master-1 to loadbalancers)
    include_role:
      name: roles/ca
      tasks_from: copy_certs_and_configs.yml
