---
- hosts: vm_mom
  vars: 
    host_key_checking: no
    kubectl_url:  https://storage.googleapis.com/kubernetes-release/release/v1.13.0/bin/linux/amd64/kubectl
  gather_facts: false
  tasks:
  - name: provision certs and tsl
    include_role:
      name: roles/ca
      tasks_from: main.yml
  - name: generate kube-proxy.kubeconfig
    include_role:
      name: roles/ca
      tasks_from: generate_kube_proxy_config.yml
  - name: generate kube-controller-manager.kubeconfig
    include_role:
      name: roles/ca
      tasks_from: generate_kube_controller_config.yml 
  - name: generate kube-scheduler.kubeconfig
    include_role:
      name: roles/ca
      tasks_from: generate_kube_scheduler_config.yml
- hosts: vm_worker_nodes
  tasks:    
  - name: Copy Remote-To-Remote (from vm-master-1 to worker-nodes)
    include_role:
      name: roles/ca
      tasks_from: copy_certs_and_configs_workers.yml
- hosts: vm_master_nodes
  tasks:    
  - name: Copy Remote-To-Remote (from vm-master-1 to master-nodes)
    include_role:
      name: roles/ca
      tasks_from: copy_certs_and_configs_masters.yml
- hosts: vm_load_balancers
  tasks:    
  - name: Copy Remote-To-Remote (from vm-master-1 to loadbalancers)
    include_role:
      name: roles/ca
      tasks_from: copy_certs_and_configs_loadbalancers.yml
