---
- hosts: vm_mom
  vars: 
    host_key_checking: no
    kubectl_url:  https://storage.googleapis.com/kubernetes-release/release/v1.13.0/bin/linux/amd64/kubectl
  gather_facts: false
  tasks:
  - name: provision certs and tsl
    include_role:
      name: roles/ca
      tasks_from: main.yml
- hosts: vm_nodes
  tasks:    
  - name: Copy Remote-To-Remote (from vm-master-1 to worker-nodes)
    include_role:
      name: roles/ca
      tasks_from: copy_certs.yml
