---
## The server needs ssh-pass in order to connect with passwords

- hosts: worker_nodes
  vars:
    working_dir: ~/workspace/kube/ansible_pi_kube
    user_group: "{{ ansible_user }}"
  remote_user: root
  gather_facts: false
  tasks:
    - name: Create token from control_node
      become: yes
      shell: "kubeadm token generate | tee /home/ubuntu/kube_control.token"
      args:
        creates: /home/ubuntu/kube_control.token
      register: register_token
      delegate_to: control_node
    - set_fact:
        token: "{{ register_token.stdout }}"
    - debug: var=token
          delegate_to: control_plane
    - name: Have worker nodes join kube cluster
      include_role:
        name: roles/kube_raspi_ubuntu
        tasks_from: worker_nodes.yml